spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZouHongxue/springcloud-config-repo
          search-paths:
          username:
          password:
          default-label: master

server:
  port: 9900
